### ISSUE TITLE
[FR] allow setting bazel-version explicitly

### ISSUE THREAD

**Issue by betaboon** [bazel-contrib/.github#21]
Currently `bazel.yaml` set's two bazel-versions "implicitly", the version from `.bazelversion` and `8.0.0rc1`. ([source](https://github.com/bazel-contrib/.github/blob/master/.github/workflows/bazel.yaml#L87-L90))

It would be great to be able to set the bazel-versions explicitly.

maybe something like this:
```yaml
jobs:
  test:
    uses: bazel-contrib/.github/.github/workflows/bazel.yaml@v6
    with:
      bazelversions: |
        [
          "6.x",
          "7.x",
          "8.0.0rc1"
        ]
```
which could lead to the list being `.bazelversion`+those versions.
